name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  paths:
    - "strapi-portfolio/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Create env file"
        run: |
          touch .env
          echo APP_KEYS=${{ secrets.STRAPI_APP_KEYS }} >> .env
          echo API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }} >> .env
          echo ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }} >> .env
          echo TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }} >> .env
          echo JWT_SECRET=${{ secrets.STRAPI_JWT_SECRET }} >> .env
          echo DATABASE_CLIENT=${{ secrets.STRAPI_DATABASE_CLIENT }} >> .env
          echo DATABASE_HOST=${{ secrets.STRAPI_DATABASE_HOST }} >> .env
          echo DATABASE_PORT=${{ secrets.STRAPI_DATABASE_PORT }} >> .env
          echo DATABASE_NAME=${{ secrets.STRAPI_DATABASE_NAME }} >> .env
          echo DATABASE_USERNAME=${{ secrets.STRAPI_DATABASE_USERNAME }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.STRAPI_DATABASE_PASSWORD }} >> .env
          echo DATABASE_SSL=false >> .env
          cat .env

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag strapi-portfolio:${{ github.run_number }}
        env:
          TAG: ${{ github.run_number }}

      - name: Save Docker image to a file
        run: docker save strapi-portfolio:${{ github.run_number }} | gzip > strapi-portfolio.tar.gz

      - name: Transfer Docker image to VM
        uses: appleboy/scp-action@master
        with:
          source: "strapi-portfolio.tar.gz"
          target: "~/app/front/"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy Docker image on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app/front
            docker load < strapi-portfolio.tar.gz
            docker stop strapi-portfolio || true
            docker rm strapi-portfolio || true
            docker run -d -p 1337:1337 --network https-net --network portfolio --name strapi-portfolio strapi-portfolio:${{ github.run_number }}
